apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: dcollioni/udagram-api-feed
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: udagram-api-feed-secret
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v0
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
