apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: LoadBalancer
